name: code-checking

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun tsc
      - run: bun eslint
