name: code-checking

on:
  pull_request:
    branches:
      - main
<<<<<<< HEAD
  push:
    branches:
      - main
=======
>>>>>>> 54200ee (adding 'on' to workflow)

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - run: bun install

  tsc:
    name: TypeScript check
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - run: bun tsc

  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - run: bun eslint